import type { Item } from '../define/classes/item.class';
import type { ReducerEntry, StateMapData } from '../types/state-map.type';
export declare class StateMap {
    stateGen: number;
    symbolGen: number;
    reduceGen: number;
    rawStates: Item[];
    debugMode: boolean;
    finalized: boolean;
    lookup: Record<string, string>;
    symbol: Record<string, string>;
    start: string;
    states: Record<string, Record<string, string>>;
    ends: Record<string, string>;
    exclude: Record<string, boolean>;
    reduceLookup: Record<string, string>;
    reducers: Record<string, ReducerEntry>;
    root: string;
    augmentedRoot: string;
    endSymbol: string;
    endToken: string;
    constructor(debug?: boolean);
    private init;
    generateState(): string;
    setRoot(name: string): void;
    createState(id: string): Record<string, string>;
    createPointer(id: string, token: string, target: string): Record<string, string>;
    generateSymbol(name: string): string;
    generateReduceId(name: string, params: number, ruleIndex: number): string;
    lookupReducer(id: string): ReducerEntry | false;
    lookupSymbol(name: string): string | false;
    setReduceState(state: string, name: string, params: number, ruleIndex: number): void;
    reset(): void;
    finalize(): boolean;
    setExcludes(exclude: unknown): void;
    importStates(definition: StateMapData): boolean;
    toObject(): StateMapData;
    exportStates(json?: boolean): StateMapData | string | null;
}
